-- Insert 50 records into the project table
INSERT INTO project (name, manager, location, start_date, end_date, description) VALUES
                                                                                     ('Project Alpha', 'Alice', 'New York', '2024-01-01', '2024-06-01', 'Description for Project Alpha'),
                                                                                     ('Project Beta', 'Bob', 'Los Angeles', '2024-02-01', '2024-07-01', 'Description for Project Beta'),
                                                                                     ('Project Gamma', 'Charlie', 'Chicago', '2024-03-01', '2024-08-01', 'Description for Project Gamma'),
                                                                                     ('Project Delta', 'David', 'Houston', '2024-04-01', '2024-09-01', 'Description for Project Delta'),
                                                                                     ('Project Epsilon', 'Eve', 'Phoenix', '2024-05-01', '2024-10-01', 'Description for Project Epsilon'),
                                                                                     ('Project Zeta', 'Frank', 'Philadelphia', '2024-06-01', '2024-11-01', 'Description for Project Zeta'),
                                                                                     ('Project Eta', 'Grace', 'San Antonio', '2024-07-01', '2024-12-01', 'Description for Project Eta'),
                                                                                     ('Project Theta', 'Hank', 'San Diego', '2024-08-01', '2025-01-01', 'Description for Project Theta'),
                                                                                     ('Project Iota', 'Ivy', 'Dallas', '2024-09-01', '2025-02-01', 'Description for Project Iota'),
                                                                                     ('Project Kappa', 'Jack', 'San Jose', '2024-10-01', '2025-03-01', 'Description for Project Kappa'),
                                                                                     ('Project Lambda', 'Ken', 'Austin', '2024-11-01', '2025-04-01', 'Description for Project Lambda'),
                                                                                     ('Project Mu', 'Lara', 'Jacksonville', '2024-12-01', '2025-05-01', 'Description for Project Mu'),
                                                                                     ('Project Nu', 'Mike', 'Fort Worth', '2025-01-01', '2025-06-01', 'Description for Project Nu'),
                                                                                     ('Project Xi', 'Nina', 'Columbus', '2025-02-01', '2025-07-01', 'Description for Project Xi'),
                                                                                     ('Project Omicron', 'Oscar', 'Charlotte', '2025-03-01', '2025-08-01', 'Description for Project Omicron'),
                                                                                     ('Project Pi', 'Paul', 'San Francisco', '2025-04-01', '2025-09-01', 'Description for Project Pi'),
                                                                                     ('Project Rho', 'Quinn', 'Indianapolis', '2025-05-01', '2025-10-01', 'Description for Project Rho'),
                                                                                     ('Project Sigma', 'Rick', 'Seattle', '2025-06-01', '2025-11-01', 'Description for Project Sigma'),
                                                                                     ('Project Tau', 'Sara', 'Denver', '2025-07-01', '2025-12-01', 'Description for Project Tau'),
                                                                                     ('Project Upsilon', 'Tom', 'Washington', '2025-08-01', '2026-01-01', 'Description for Project Upsilon'),
                                                                                     ('Project Phi', 'Uma', 'Boston', '2025-09-01', '2026-02-01', 'Description for Project Phi'),
                                                                                     ('Project Chi', 'Vince', 'El Paso', '2025-10-01', '2026-03-01', 'Description for Project Chi'),
                                                                                     ('Project Psi', 'Wendy', 'Detroit', '2025-11-01', '2026-04-01', 'Description for Project Psi'),
                                                                                     ('Project Omega', 'Xander', 'Nashville', '2025-12-01', '2026-05-01', 'Description for Project Omega'),
                                                                                     ('Project Alpha 2', 'Yara', 'Memphis', '2026-01-01', '2026-06-01', 'Description for Project Alpha 2'),
                                                                                     ('Project Beta 2', 'Zack', 'Portland', '2026-02-01', '2026-07-01', 'Description for Project Beta 2'),
                                                                                     ('Project Gamma 2', 'Alice', 'Oklahoma City', '2026-03-01', '2026-08-01', 'Description for Project Gamma 2'),
                                                                                     ('Project Delta 2', 'Bob', 'Las Vegas', '2026-04-01', '2026-09-01', 'Description for Project Delta 2'),
                                                                                     ('Project Epsilon 2', 'Charlie', 'Louisville', '2026-05-01', '2026-10-01', 'Description for Project Epsilon 2'),
                                                                                     ('Project Zeta 2', 'David', 'Baltimore', '2026-06-01', '2026-11-01', 'Description for Project Zeta 2'),
                                                                                     ('Project Eta 2', 'Eve', 'Milwaukee', '2026-07-01', '2026-12-01', 'Description for Project Eta 2'),
                                                                                     ('Project Theta 2', 'Frank', 'Albuquerque', '2026-08-01', '2027-01-01', 'Description for Project Theta 2'),
                                                                                     ('Project Iota 2', 'Grace', 'Tucson', '2026-09-01', '2027-02-01', 'Description for Project Iota 2'),
                                                                                     ('Project Kappa 2', 'Hank', 'Fresno', '2026-10-01', '2027-03-01', 'Description for Project Kappa 2'),
                                                                                     ('Project Lambda 2', 'Ivy', 'Sacramento', '2026-11-01', '2027-04-01', 'Description for Project Lambda 2'),
                                                                                     ('Project Mu 2', 'Jack', 'Kansas City', '2026-12-01', '2027-05-01', 'Description for Project Mu 2'),
                                                                                     ('Project Nu 2', 'Ken', 'Mesa', '2027-01-01', '2027-06-01', 'Description for Project Nu 2'),
                                                                                     ('Project Xi 2', 'Lara', 'Atlanta', '2027-02-01', '2027-07-01', 'Description for Project Xi 2'),
                                                                                     ('Project Omicron 2', 'Mike', 'Omaha', '2027-03-01', '2027-08-01', 'Description for Project Omicron 2'),
                                                                                     ('Project Pi 2', 'Nina', 'Colorado Springs', '2027-04-01', '2027-09-01', 'Description for Project Pi 2'),
                                                                                     ('Project Rho 2', 'Oscar', 'Raleigh', '2027-05-01', '2027-10-01', 'Description for Project Rho 2'),
                                                                                     ('Project Sigma 2', 'Paul', 'Miami', '2027-06-01', '2027-11-01', 'Description for Project Sigma 2'),
                                                                                     ('Project Tau 2', 'Quinn', 'Virginia Beach', '2027-07-01', '2027-12-01', 'Description for Project Tau 2'),
                                                                                     ('Project Upsilon 2', 'Rick', 'Oakland', '2027-08-01', '2028-01-01', 'Description for Project Upsilon 2'),
                                                                                     ('Project Phi 2', 'Sara', 'Minneapolis', '2027-09-01', '2028-02-01', 'Description for Project Phi 2');